# Macro file for example B2
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
/PHONON/det/setGDMLFile gdml/scintillator_shield/ScintillatorShield.gdml
/PHONON/run/useHDF5 false
#/PHONON/run/setOutputFile shielded_testfiletypesetting
#/PHONON/run/setOutputFile shielded_testfiletypesetting_higherEprimary
/PHONON/run/setOutputFile gammas_SNSroom.root
#/PHONON/run/setOutputFile scrap.root

# Initialize kernel
/run/initialize
#
# Default kinematics: 
# proton 3 GeV in direction (0.,0.,1.)
# 1 event with tracking/verbose
#
#/tracking/verbose 1
#/run/beamOn 1
#
# 1 event with printing hits
#
/tracking/verbose 0
/hits/verbose 2
#/run/beamOn 1
#
# set target and chamber material
#
#/B2/det/setTargetMaterial G4_WATER
#/B2/det/setChamberMaterial G4_Ar
#/run/beamOn 3
# 
# set a magnetic field and max allowed step length
# 3 event with printing hits
#
#/globalField/verbose 1
#/globalField/setValue 0.2 0 0 tesla
#/B2/det/stepMax 1.0 mm
#/gun/energy 0.3 GeV
#/run/beamOn 3
#
# muon 300 MeV in the direction (0.,0.,1.)
# 3 event with detailed printing
#

/g4cmp/producePhonons 0
/g4cmp/produceCharges 0
/g4cmp/maxLukePhonons 0
#/g4cmp/sampleLuke 0.00001
/g4cmp/phononBounces 1
/g4cmp/minEPhonons 0.001 eV
#/g4cmp/verbose 1

/process/inactivate phononScattering
/process/inactivate phononDownconversion

/PHONONEvent/offset 0

/gps/particle gamma

/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 0.05 0.00316
/gps/hist/point 0.10 0.0928
/gps/hist/point 0.15 0.1101
/gps/hist/point 0.20 0.0889
/gps/hist/point 0.25 0.0804
/gps/hist/point 0.30 0.0609
/gps/hist/point 0.35 0.0431
/gps/hist/point 0.40 0.0453
/gps/hist/point 0.45 0.0249
/gps/hist/point 0.50 0.0235
/gps/hist/point 0.55 0.0230
/gps/hist/point 0.60 0.0261
/gps/hist/point 0.65 0.0402
/gps/hist/point 0.70 0.0125
/gps/hist/point 0.75 0.0137
/gps/hist/point 0.80 0.0170
/gps/hist/point 0.85 0.0114
/gps/hist/point 0.90 0.0100
/gps/hist/point 0.95 0.0188
/gps/hist/point 1.00 0.0144
/gps/hist/point 1.05 0.0072
/gps/hist/point 1.10 0.0070
/gps/hist/point 1.15 0.0181
/gps/hist/point 1.20 0.0068
/gps/hist/point 1.25 0.0106
/gps/hist/point 1.30 0.0062
/gps/hist/point 1.35 0.0050
/gps/hist/point 1.40 0.0089
/gps/hist/point 1.45 0.0078
/gps/hist/point 1.50 0.0890
/gps/hist/point 1.55 0.0050
/gps/hist/point 1.60 0.0035
/gps/hist/point 1.65 0.0028
/gps/hist/point 1.70 0.0025
/gps/hist/point 1.75 0.0040
/gps/hist/point 1.80 0.0161
/gps/hist/point 1.85 0.0031
/gps/hist/point 1.90 0.0011
/gps/hist/point 1.95 0.0005
/gps/hist/point 2.00 0.0006
/gps/hist/point 2.05 0.0005
/gps/hist/point 2.10 0.0006
/gps/hist/point 2.15 0.0024
/gps/hist/point 2.20 0.0059
/gps/hist/point 2.25 0.0007
/gps/hist/point 2.30 0.0003
/gps/hist/point 2.35 0.0004
/gps/hist/point 2.40 0.0022
/gps/hist/point 2.45 0.0002
/gps/hist/point 2.50 0.0003
/gps/hist/point 2.55 0.0003
/gps/hist/point 2.60 0.0199
/gps/hist/inter Lin

/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre -0.51 0.0 0.0 m
/gps/pos/halfx 0.5 m
/gps/pos/halfy 0.5 m
/gps/pos/rot1 0 0 1
/gps/pos/rot2 0 1 0
/gps/ang/type cos
#/gps/pos/confine NeutronPlaneVol

/run/beamOn 750000
#/run/beamOn 1000
